from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np
import spacy
import joblib
import logging
import os
import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware


# CONFIGURATION

app = FastAPI(title="🩺 Medical Triage Severity API", version="1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # For development: allow all origins. In production, replace with your frontend URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Globals for model and embedder
clf = None
embedder = None

LOG_FILE = "triage_logs.txt"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Use merged dataset if available (generated by generate_training_data.py), else original
_MERGED = os.path.join(BASE_DIR, "triage_merged.csv")
_ORIGINAL = os.path.join(BASE_DIR, "triage2.csv")
DATA_PATH = _MERGED if os.path.exists(_MERGED) else _ORIGINAL
MODEL_PATH = os.path.join(BASE_DIR, "severity_classifier.joblib")
EMBEDDER_PATH = os.path.join(BASE_DIR, "embedder_model")

# Logging setup
logging.basicConfig(
    filename=LOG_FILE,
    level=logging.INFO,
    format="%(asctime)s - %(message)s"
)


# INPUT MODEL
class TriageInput(BaseModel):
    text: str

# ─────────────────────────────────────────────────────────────────────────────
# KEYWORD OVERRIDE TABLES
# These ensure the ML model never under-classifies clearly serious conditions.
# Based on app/triage_conditions.py — single source of truth for clinical rules.
# ─────────────────────────────────────────────────────────────────────────────
_CRITICAL_KW = [
    "heart attack", "cardiac arrest", "heart stopped", "no pulse",
    "aortic dissection", "aortic rupture",
    "stroke", "brain bleed", "thunderclap headache", "worst headache of my life",
    "seizure", "fitting", "convulsion", "unresponsive", "unconscious",
    "status epilepticus", "subdural", "subarachnoid",
    "can't breathe", "cannot breathe", "not breathing", "stopped breathing",
    "airway blocked", "choking", "respiratory arrest",
    "carbon monoxide", "co poisoning",
    "massive bleeding", "uncontrolled bleeding", "arterial bleed",
    "bone through skin", "open skull", "skull fracture",
    "crush injury", "traumatic amputation",
    "hit by car", "fell from height", "high-energy trauma",
    "electrocution", "high voltage",
    "airway burn", "face burn", "third degree burn",
    "overdose", "ingested poison",
    "snake bite", "organophosphate", "pesticide poisoning",
    "anaphylaxis", "severe allergic reaction", "throat closing", "tongue swelling",
    "epipen", "epinephrine",
    "eclampsia", "placenta praevia", "placental abruption", "cord prolapse",
    "uterine rupture", "ectopic rupture", "postpartum haemorrhage",
    "suicidal", "want to die", "end my life", "kill myself", "taking my life",
    "harming myself", "suicide attempt",
    "septic shock", "toxic shock",
    "heat stroke", "diabetic coma", "dka unconscious",
    "meningococcal", "non-blanching rash",
    "vomiting blood", "coughing blood",
    "child not breathing", "baby unresponsive", "infant not waking",
]

_HIGH_KW = [
    "broken bone", "broken", "fracture", "fractured",
    "compound fracture", "open fracture", "stress fracture", "hairline fracture",
    "dislocated", "dislocation", "popped out", "out of socket",
    "torn ligament", "torn tendon", "torn muscle", "torn acl", "torn mcl",
    "ruptured tendon", "ruptured achilles", "achilles tear",
    "separated shoulder", "snapped", "felt a pop", "heard a crack",
    "cannot move", "can't move", "unable to move",
    "cannot walk", "can't walk", "unable to bear weight",
    "numbness after injury", "paralysis", "paralyzed", "paralysed",
    "deep cut", "deep laceration", "gaping wound",
    "won't stop bleeding", "bleeding won't stop", "spurting blood",
    "needs stitches",
    "second degree burn", "third degree", "blistering burn",
    "chemical burn", "acid burn",
    "head injury", "hit head", "concussion", "loss of consciousness", "blacked out",
    "vomited after head injury",
    "appendicitis", "appendix pain", "appendix",
    "bowel obstruction", "twisted bowel",
    "tarry stool", "melaena", "black stool with blood",
    "pancreatitis", "severe abdominal pain",
    "severe chest pain", "chest pressure", "crushing chest",
    "pain in left arm", "jaw pain with chest",
    "asthma attack", "asthma not responding",
    "blue lips", "cyanosis", "difficulty breathing at rest",
    "sudden vision loss", "sudden blindness", "face drooping",
    "arm weakness", "slurred speech", "facial droop",
    "meningitis", "stiff neck with fever", "photophobia fever",
    "spreading redness", "necrotising", "cellulitis spreading",
    "infection spreading",
    "high fever", "fever above 39", "fever above 40",
    "fever over 39", "fever over 40",
    "eye injury", "chemical in eye", "acid in eye",
    "ectopic pregnancy", "heavy bleeding pregnancy",
    "pre-eclampsia", "testicular torsion", "ovarian torsion",
    "cannot urinate", "can't urinate", "urinary retention", "priapism",
    "peritonsillar abscess", "unable to swallow",
    "infant fever", "baby fever", "newborn fever",
    "febrile convulsion", "child seizing",
]

_SEVERITY_RANK = {"LOW": 0, "MEDIUM": 1, "HIGH": 2, "CRITICAL": 3}


def _keyword_override(text: str) -> str | None:
    """Return forced severity if keywords demand it, else None."""
    p = text.lower()
    if any(k in p for k in _CRITICAL_KW):
        return "CRITICAL"
    if any(k in p for k in _HIGH_KW):
        return "HIGH"
    return None


# TEXT PREPROCESSING
nlp = spacy.load("en_core_web_sm")


def preprocess(text: str) -> str:
    doc = nlp(text.lower())
    return " ".join([t.lemma_ for t in doc if t.is_alpha and not t.is_stop])


# LOAD OR TRAIN MODEL
def load_or_train_model():
    if os.path.exists(MODEL_PATH) and os.path.exists(EMBEDDER_PATH):
        clf_local = joblib.load(MODEL_PATH)
        embedder_local = SentenceTransformer(EMBEDDER_PATH)
        print("✅ Model and embedder loaded.")
    else:
        print(" Training model for the first time...")
        df = pd.read_csv(DATA_PATH)
        df["text"] = df["text"].astype(str).fillna("")
        df["cleaned"] = df["text"].apply(preprocess)

        X = df["cleaned"].tolist()
        y = df["severity"].tolist()

        embedder_local = SentenceTransformer("all-MiniLM-L6-v2")
        X_embeddings = embedder_local.encode(X, show_progress_bar=True)

        X_train, X_test, y_train, y_test = train_test_split(
            X_embeddings, y, test_size=0.2, random_state=42, stratify=y
        )

        clf_local = LogisticRegression(max_iter=2000, class_weight="balanced", C=2.0)
        clf_local.fit(X_train, y_train)

        y_pred = clf_local.predict(X_test)
        print("\n🔍 Classification Report:\n", classification_report(y_test, y_pred))

        joblib.dump(clf_local, MODEL_PATH)
        embedder_local.save(EMBEDDER_PATH)
        print("✅ Model and embedder saved.")

    return clf_local, embedder_local


# STARTUP EVENT
@app.on_event("startup")
def startup_event():
    global clf, embedder
    clf, embedder = load_or_train_model()


# ROUTES
@app.get("/")
def home():
    return {"message": "🩺 Triage Severity Classifier is running", "version": "1.0"}

@app.post("/predict")
async def predict(data: TriageInput):
    try:
        user_input = data.text.strip()
        cleaned = preprocess(user_input)
        user_vec = embedder.encode([cleaned])
        pred = clf.predict(user_vec)[0]
        probs = clf.predict_proba(user_vec)[0]
        conf = float(np.max(probs))

        # Apply keyword override — bump severity up if keywords demand it.
        # The ML model may under-classify serious injuries or emergencies;
        # the override ensures clinical safety standards are always met.
        override = _keyword_override(user_input)
        if override and _SEVERITY_RANK.get(override, 0) > _SEVERITY_RANK.get(pred.upper(), 0):
            logging.info(
                f"Input: {user_input} | ML: {pred} ({conf:.2f}) | Override → {override}"
            )
            pred = override
            conf = 1.0  # Override is deterministic — report as 100% confident
        else:
            logging.info(f"Input: {user_input} | Prediction: {pred} | Confidence: {conf:.2f}")

        result = {
            "input": user_input,
            "predicted_severity": pred,
            "confidence": round(conf, 2)
        }

        return JSONResponse(content=result)

    except Exception as e:
        logging.error(f"Error processing input: {e}")
        return JSONResponse(content={"error": str(e)}, status_code=500)

# # RUN APP
# if __name__ == "__main__":
#     # Run Uvicorn server directly
#     uvicorn.run("non-final-draft:app", host="0.0.0.0", port=10000)
